//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ahmad.OnlineShop.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ahmad.OnlineShop.Domain.Resources.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته‌بندی نمی‌تواند به خودش یا زیرمجموعه‌هایش اشاره کند..
        /// </summary>
        internal static string CategoryCircularReferenceException {
            get {
                return ResourceManager.GetString("CategoryCircularReferenceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته‌بندی یافت نشد.
        /// </summary>
        internal static string CategoryNotFoundException {
            get {
                return ResourceManager.GetString("CategoryNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام دسته‌بندی نمی‌تواند خالی باشد..
        /// </summary>
        internal static string EmptyCategoryNameException {
            get {
                return ResourceManager.GetString("EmptyCategoryNameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام و نام خانوادگی نمی‌توانند خالی باشند..
        /// </summary>
        internal static string EmptyNameException {
            get {
                return ResourceManager.GetString("EmptyNameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل نمی‌تواند خالی باشد..
        /// </summary>
        internal static string EmptyPhoneNumberException {
            get {
                return ResourceManager.GetString("EmptyPhoneNumberException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام محصول نمی‌تواند خالی باشد.
        /// </summary>
        internal static string EmptyProductNameException {
            get {
                return ResourceManager.GetString("EmptyProductNameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر از قبل وجود دارد..
        /// </summary>
        internal static string ExistingUserException {
            get {
                return ResourceManager.GetString("ExistingUserException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلید باکت نمی‌تواند خالی باشد..
        /// </summary>
        internal static string ImageInvalidBucketKeyException {
            get {
                return ResourceManager.GetString("ImageInvalidBucketKeyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترتیب نمایش نمی‌تواند منفی باشد..
        /// </summary>
        internal static string ImageInvalidSortOrderException {
            get {
                return ResourceManager.GetString("ImageInvalidSortOrderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس تصویر نمی‌تواند خالی باشد..
        /// </summary>
        internal static string ImageInvalidUrlException {
            get {
                return ResourceManager.GetString("ImageInvalidUrlException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصویر یافت نشد..
        /// </summary>
        internal static string ImageNotFoundException {
            get {
                return ResourceManager.GetString("ImageNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری یا رمز عبور نامعتبر است..
        /// </summary>
        internal static string IncorrectPasswordException {
            get {
                return ResourceManager.GetString("IncorrectPasswordException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;موجودی کافی برای انجام این عملیات وجود ندارد..
        /// </summary>
        internal static string InsufficientStockException {
            get {
                return ResourceManager.GetString("InsufficientStockException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس تصویر نامعتبر است..
        /// </summary>
        internal static string InvalidImageUrlException {
            get {
                return ResourceManager.GetString("InvalidImageUrlException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی نامعتبر است..
        /// </summary>
        internal static string InvalidNationalCodeException {
            get {
                return ResourceManager.GetString("InvalidNationalCodeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت شماره موبایل نامعتبر است..
        /// </summary>
        internal static string InvalidPhoneNumberException {
            get {
                return ResourceManager.GetString("InvalidPhoneNumberException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت محصول باید بزرگ‌تر از صفر باشد.
        /// </summary>
        internal static string InvalidPriceException {
            get {
                return ResourceManager.GetString("InvalidPriceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده معتبر نیست..
        /// </summary>
        internal static string InvalidQuantityException {
            get {
                return ResourceManager.GetString("InvalidQuantityException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات رزرو معتبر نیست..
        /// </summary>
        internal static string InvalidReserveException {
            get {
                return ResourceManager.GetString("InvalidReserveException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار رزرو باید بزرگ‌تر از صفر باشد..
        /// </summary>
        internal static string InvalidReserveQuantityException {
            get {
                return ResourceManager.GetString("InvalidReserveQuantityException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد تصاویر از حداکثر مجاز (۱۰ تصویر) بیشتر نمی‌تواند باشد..
        /// </summary>
        internal static string MaxImagesExceededException {
            get {
                return ResourceManager.GetString("MaxImagesExceededException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ رزروی برای آزادسازی وجود ندارد..
        /// </summary>
        internal static string NothingToReleaseException {
            get {
                return ResourceManager.GetString("NothingToReleaseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور جدید و تکرار آن مطابقت ندارند.
        /// </summary>
        internal static string PasswordMismatchException {
            get {
                return ResourceManager.GetString("PasswordMismatchException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یک تصویر اصلی از قبل وجود دارد..
        /// </summary>
        internal static string PrimaryImageExistsException {
            get {
                return ResourceManager.GetString("PrimaryImageExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .محصول در حال حاضر فعال است.
        /// </summary>
        internal static string ProductAlreadyActiveException {
            get {
                return ResourceManager.GetString("ProductAlreadyActiveException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصول در حال حاضر آرشیو شده است.
        /// </summary>
        internal static string ProductAlreadyArchivedException {
            get {
                return ResourceManager.GetString("ProductAlreadyArchivedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصول در حال حاضر غیرفعال است.
        /// </summary>
        internal static string ProductAlreadyInactiveException {
            get {
                return ResourceManager.GetString("ProductAlreadyInactiveException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصول یافت نشد..
        /// </summary>
        internal static string ProductNotFoundException {
            get {
                return ResourceManager.GetString("ProductNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فردی با این نامکاربری قبلا ثبات نام کرده است .
        /// </summary>
        internal static string UserExistException {
            get {
                return ResourceManager.GetString("UserExistException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر یافت نشد ..
        /// </summary>
        internal static string UserNotFoundException {
            get {
                return ResourceManager.GetString("UserNotFoundException", resourceCulture);
            }
        }

        internal static string AdminNotFoundException {
            get {
                return ResourceManager.GetString("AdminNotFoundException", resourceCulture);
            }
        }

        internal static string AdminEmailAlreadyExistsException {
            get {
                return ResourceManager.GetString("AdminEmailAlreadyExistsException", resourceCulture);
            }
        }

        internal static string AdminInvalidEmailException {
            get {
                return ResourceManager.GetString("AdminInvalidEmailException", resourceCulture);
            }
        }

        internal static string AdminInvalidNameException {
            get {
                return ResourceManager.GetString("AdminInvalidNameException", resourceCulture);
            }
        }

        internal static string AdminAlreadyActiveException {
            get {
                return ResourceManager.GetString("AdminAlreadyActiveException", resourceCulture);
            }
        }

        internal static string AdminAlreadyInactiveException {
            get {
                return ResourceManager.GetString("AdminAlreadyInactiveException", resourceCulture);
            }
        }

        internal static string ReportNotFoundException {
            get {
                return ResourceManager.GetString("ReportNotFoundException", resourceCulture);
            }
        }

        internal static string ReportAlreadyCompletedException {
            get {
                return ResourceManager.GetString("ReportAlreadyCompletedException", resourceCulture);
            }
        }

        internal static string AuditInvalidActionException {
            get {
                return ResourceManager.GetString("AuditInvalidActionException", resourceCulture);
            }
        }

        internal static string AuditInvalidEntityException {
            get {
                return ResourceManager.GetString("AuditInvalidEntityException", resourceCulture);
            }
        }

        internal static string CreditLimitNotFoundException {
            get { return ResourceManager.GetString("CreditLimitNotFoundException", resourceCulture); }
        }

        internal static string InsufficientCreditException {
            get { return ResourceManager.GetString("InsufficientCreditException", resourceCulture); }
        }

        internal static string InvalidCreditLimitAmountException {
            get { return ResourceManager.GetString("InvalidCreditLimitAmountException", resourceCulture); }
        }

        internal static string NegativeCreditException {
            get { return ResourceManager.GetString("NegativeCreditException", resourceCulture); }
        }

        internal static string BnplContractNotFoundException {
            get { return ResourceManager.GetString("BnplContractNotFoundException", resourceCulture); }
        }

        internal static string BnplContractAlreadyCancelledException {
            get { return ResourceManager.GetString("BnplContractAlreadyCancelledException", resourceCulture); }
        }

        internal static string BnplContractAlreadyCompletedException {
            get { return ResourceManager.GetString("BnplContractAlreadyCompletedException", resourceCulture); }
        }

        internal static string BnplContractNotActiveException {
            get { return ResourceManager.GetString("BnplContractNotActiveException", resourceCulture); }
        }

        internal static string InvalidInstallmentCountException {
            get { return ResourceManager.GetString("InvalidInstallmentCountException", resourceCulture); }
        }

        internal static string InvalidTotalAmountException {
            get { return ResourceManager.GetString("InvalidTotalAmountException", resourceCulture); }
        }

        internal static string InstallmentNotFoundException {
            get { return ResourceManager.GetString("InstallmentNotFoundException", resourceCulture); }
        }

        internal static string InstallmentAlreadyPaidException {
            get { return ResourceManager.GetString("InstallmentAlreadyPaidException", resourceCulture); }
        }

        internal static string InstallmentInvalidAmountException {
            get { return ResourceManager.GetString("InstallmentInvalidAmountException", resourceCulture); }
        }

        internal static string OrderNotFoundException {
            get { return ResourceManager.GetString("OrderNotFoundException", resourceCulture); }
        }
        internal static string OrderNoItemsException {
            get { return ResourceManager.GetString("OrderNoItemsException", resourceCulture); }
        }
        internal static string OrderAlreadyCancelledException {
            get { return ResourceManager.GetString("OrderAlreadyCancelledException", resourceCulture); }
        }
        internal static string OrderAlreadyDeliveredException {
            get { return ResourceManager.GetString("OrderAlreadyDeliveredException", resourceCulture); }
        }
        internal static string OrderInvalidStatusTransitionException {
            get { return ResourceManager.GetString("OrderInvalidStatusTransitionException", resourceCulture); }
        }
        internal static string OrderItemNotFoundException {
            get { return ResourceManager.GetString("OrderItemNotFoundException", resourceCulture); }
        }
        internal static string OrderItemInvalidQuantityException {
            get { return ResourceManager.GetString("OrderItemInvalidQuantityException", resourceCulture); }
        }
        internal static string OrderItemInvalidUnitPriceException {
            get { return ResourceManager.GetString("OrderItemInvalidUnitPriceException", resourceCulture); }
        }
        internal static string PaymentNotFoundException {
            get { return ResourceManager.GetString("PaymentNotFoundException", resourceCulture); }
        }
        internal static string PaymentAmountMismatchException {
            get { return ResourceManager.GetString("PaymentAmountMismatchException", resourceCulture); }
        }
        internal static string PaymentInvalidAmountException {
            get { return ResourceManager.GetString("PaymentInvalidAmountException", resourceCulture); }
        }
        internal static string OrderCannotConfirmWithoutPaymentException {
            get { return ResourceManager.GetString("OrderCannotConfirmWithoutPaymentException", resourceCulture); }
        }
        internal static string RoleNotFoundException {
            get { return ResourceManager.GetString("RoleNotFoundException", resourceCulture); }
        }
        internal static string InvalidRefreshTokenException {
            get { return ResourceManager.GetString("InvalidRefreshTokenException", resourceCulture); }
        }
    }
}
